package org.ohnlp.ir.cat.ehr.datasource;

import org.apache.beam.sdk.Pipeline;
import org.apache.beam.sdk.schemas.Schema;
import org.apache.beam.sdk.transforms.DoFn;
import org.apache.beam.sdk.transforms.ParDo;
import org.apache.beam.sdk.values.PCollection;
import org.apache.beam.sdk.values.Row;
import org.hl7.fhir.r4.model.*;
import org.ohnlp.ir.cat.DataConnection;

import java.util.Collections;
import java.util.Date;
import java.util.Set;

public class OHDSICDMDataSource implements EHRDataSource {

    private DataConnection ehrDataConnection;
    private String cdmSchemaName;

    @Override
    public PCollection<Condition> getConditions(Pipeline pipeline) {
        return ehrDataConnection.getForQueryAndSchema(
                pipeline,
                "SELECT condition_occurrence_id, " +
                        "person_id, " +
                        "condition_concept_id, " +
                        "condition_start_date FROM " + cdmSchemaName + ".condition_occurrence ",
                Schema.builder()
                        .addFields(
                                Schema.Field.of("condition_occurrence_id", Schema.FieldType.INT64),
                                Schema.Field.of("person_id", Schema.FieldType.INT64),
                                Schema.Field.of("condition_concept_id", Schema.FieldType.INT32),
                                Schema.Field.of("condition_start_date", Schema.FieldType.DATETIME)
                        ).build()
        ).apply("Convert Condition Read to FHIR", ParDo.of(
                new DoFn<Row, Condition>() {
                    @ProcessElement
                    public void process(@Element Row in, OutputReceiver<Condition> out) {
                        String recordID = in.getInt64("condition_occurrence_id") + "";
                        String personID = in.getInt64("person_id") + "";
                        String conditionConceptID = in.getInt32("condition_concept_id") + "";
                        Date dtm = new Date(in.getDateTime("condition_start_date").getMillis());
                        Condition cdn = new Condition();
                        cdn.setId(recordID);
                        cdn.setSubject(new Reference().setIdentifier(new Identifier().setValue(personID)));
                        cdn.setCode(
                                new CodeableConcept().addCoding(
                                        new Coding(
                                                "https://athena.ohdsi.org/",
                                                conditionConceptID,
                                                "Autogenerated OHDSI Mapping")) // TODO better mapping/descriptions
                        );
                        cdn.setRecordedDate(dtm);
                        out.output(cdn);
                    }
                }
        ));
    }

    @Override
    public PCollection<MedicationStatement> getMedications(Pipeline pipeline) {
        return ehrDataConnection.getForQueryAndSchema(
                pipeline,
                "SELECT drug_exposure_id, " +
                        "person_id, " +
                        "drug_concept_id, " +
                        "drug_exposure_start_date," +
                        "drug_exposure_end_date FROM " + cdmSchemaName + ".drug_exposure ",
                Schema.builder()
                        .addFields(
                                Schema.Field.of("drug_exposure_id", Schema.FieldType.INT64),
                                Schema.Field.of("person_id", Schema.FieldType.INT64),
                                Schema.Field.of("drug_concept_id", Schema.FieldType.INT32),
                                Schema.Field.of("drug_exposure_start_date", Schema.FieldType.DATETIME),
                                Schema.Field.of("drug_exposure_end_date", Schema.FieldType.DATETIME)
                        ).build()
        ).apply("Convert Drug Exposure Read to FHIR", ParDo.of(
                new DoFn<Row, MedicationStatement>() {
                    @ProcessElement
                    public void process(@Element Row in, OutputReceiver<MedicationStatement> out) {
                        String recordID = in.getInt64("drug_exposure_id") + "";
                        String personID = in.getInt64("person_id") + "";
                        String drugConceptId = in.getInt32("drug_concept_id") + "";
                        Date dtm = new Date(in.getDateTime("drug_exposure_start_date").getMillis());
                        // TODO see about mapping date ends? there doesn't seem to currently be a target in FHIR somehow (or am just blind)
                        MedicationStatement ms = new MedicationStatement();
                        ms.setId(recordID);
                        ms.setSubject(new Reference().setIdentifier(new Identifier().setValue(personID)));
                        ms.setMedication(
                                new CodeableConcept().addCoding(
                                        new Coding(
                                                "https://athena.ohdsi.org/",
                                                drugConceptId,
                                                "Autogenerated OHDSI Mapping")) // TODO
                        );
                        ms.setDateAsserted(dtm);
                        out.output(ms);
                    }
                }
        ));    }

    @Override
    public PCollection<Procedure> getProcedures(Pipeline pipeline) {
        return ehrDataConnection.getForQueryAndSchema(
                pipeline,
                "SELECT procedure_occurrence_id, " +
                        "person_id, " +
                        "procedure_concept_id, " +
                        "procedure_date FROM " + cdmSchemaName + ".procedure_occurrence",
                Schema.builder()
                        .addFields(
                                Schema.Field.of("procedure_occurrence_id", Schema.FieldType.INT64),
                                Schema.Field.of("person_id", Schema.FieldType.INT64),
                                Schema.Field.of("procedure_concept_id", Schema.FieldType.INT32),
                                Schema.Field.of("procedure_date", Schema.FieldType.DATETIME)
                        ).build()
        ).apply("Convert Procedure Read to FHIR", ParDo.of(
                new DoFn<Row, Procedure>() {
                    @ProcessElement
                    public void process(@Element Row in, OutputReceiver<Procedure> out) {
                        String recordID = in.getInt64("procedure_occurrence_id") + "";
                        String personID = in.getInt64("person_id") + "";
                        String conceptID = in.getInt32("procedure_concept_id") + "";
                        Date dtm = new Date(in.getDateTime("procedure_date").getMillis());
                        Procedure prc = new Procedure();
                        prc.setId(recordID);
                        prc.setSubject(new Reference().setIdentifier(new Identifier().setValue(personID)));
                        prc.setCode(
                                new CodeableConcept().addCoding(
                                        new Coding(
                                                "https://athena.ohdsi.org/",
                                                conceptID,
                                                "Autogenerated OHDSI Mapping")) // TODO better mapping/descriptions
                        );
                        prc.setPerformed(new DateTimeType(dtm));
                        out.output(prc);
                    }
                }
        ));
    }

    @Override
    public PCollection<Observation> getObservations(Pipeline pipeline) {
        return ehrDataConnection.getForQueryAndSchema(
                pipeline,
                "SELECT observation_id, " +
                        "person_id, " +
                        "observation_concept_id, " +
                        "observation_date," +
                        "value_as_number," +
                        "value_as_string FROM " + cdmSchemaName + ".procedure_occurrence",
                Schema.builder()
                        .addFields(
                                Schema.Field.of("observation_id", Schema.FieldType.INT64),
                                Schema.Field.of("person_id", Schema.FieldType.INT64),
                                Schema.Field.of("observation_concept_id", Schema.FieldType.INT32),
                                Schema.Field.of("observation_date", Schema.FieldType.DATETIME),
                                Schema.Field.of("value_as_number", Schema.FieldType.FLOAT),
                                Schema.Field.of("value_as_string", Schema.FieldType.STRING)
                        ).build()
        ).apply("Convert Observation Read to FHIR", ParDo.of(
                new DoFn<Row, Observation>() {
                    @ProcessElement
                    public void process(@Element Row in, OutputReceiver<Observation> out) {
                        String recordID = in.getInt64("observation_id") + "";
                        String personID = in.getInt64("person_id") + "";
                        String conceptID = in.getInt32("observation_concept_id") + "";
                        Date dtm = new Date(in.getDateTime("observation_date").getMillis());
                        Observation obs = new Observation();
                        obs.setId(recordID);
                        obs.setSubject(new Reference().setIdentifier(new Identifier().setValue(personID)));
                        obs.setCode(
                                new CodeableConcept().addCoding(
                                        new Coding(
                                                "https://athena.ohdsi.org/",
                                                conceptID,
                                                "Autogenerated OHDSI Mapping")) // TODO better mapping/descriptions
                        );
                        obs.setIssued(dtm);
                        out.output(obs);
                    }
                }
        ));
    }
}
